# SPDX-FileCopyrightText: 2021 Siemens AG
#
# SPDX-License-Identifier: MIT

ubuntu-jammy:
  image: ubuntu:jammy
  stage: build
  before_script:
    - ./ci/setup.sh
    - ./ci/install-src-deps.sh
  script:
    - if [ $CI_COMMIT_BRANCH == "coverity_scan" ]; then ./ci/coverity.sh;fi
    - ./ci/test-configs.sh

reuse:
  needs: []
  stage: test
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
